=== TonyApuzzo/fuzzyjoin/fuzzyjoin-hadoop/src/test/scripts/rwe/SIGMOD-2010-RWE.dtd
<!-- The top-level element must include:
     - ID and title of your paper
     - At least one among: a machine, and a network of machines. These 
     represent the hadware used in the experiments.
     - Optionally, various softwares required to run your experiments
     (other than the software you provided in the FTP site)
     - For each experiments which the committee should attempt to repeat,
     an experiment element.
     - For each experiment which you consider unrepeatable, a
     nonrepexperiment element explaining briefly why. 
     - Optionally, a comment element where you can send us your comments
     on the repeatability assessment procedure.
-->
<!ELEMENT experiments_description (paper, machine*,software*,network*,experiment*, nonrepexperiment*, comment?)>

<!-- Specify the id and name of your SIGMOD 2010 paper.
-->
<!ELEMENT paper EMPTY>
<!ATTLIST paper id CDATA #REQUIRED title CDATA #REQUIRED> 

<!-- Use machine to describe an individual computer used in the experiments. 
     An experiment requiring several machines should be described using a 
     network element - see below. 
-->
<!ELEMENT machine (hardware, os)>
<!ATTLIST machine id ID #REQUIRED>

<!-- Use hardware to describe a machine's hardware.
     On Linux machines, hardware information can be found by typing dmesg 
     shortly after rebooting.
     On Windows machines, it can be found under the Control Panel. 
     What is important for us is the resources actually available for the
     experiment. For instance, if your machine has 2GB of RAM but you only
     allowed your software to use 1GB for an experiment, declare 1GB here.
-->
<!ELEMENT hardware (class, proc, memory, disk, (comment)?)>
<!ELEMENT class (#PCDATA)> <!-- e.g., laptop, desktop, workstation, server, etc. -->
<!-- On many Linux machines, processor information can be found in 
     the file /proc/cpuinfo. -->
<!ELEMENT proc (make, model, cores, bit, GHz)>
<!ATTLIST proc count CDATA #REQUIRED>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT cores (#PCDATA)>
<!ELEMENT bit (#PCDATA)>
<!ELEMENT GHz (#PCDATA)>
<!ELEMENT memory EMPTY>
<!ATTLIST memory megabytes CDATA #REQUIRED>
<!ELEMENT disk (interface, gigabytes, RPM)>
<!ATTLIST disk count CDATA #REQUIRED RAIDlevel CDATA #REQUIRED>
<!ELEMENT interface (#PCDATA)>
<!ELEMENT gigabytes (#PCDATA)> 
<!ELEMENT RPM (#PCDATA)> 

<!-- Use os to describe an OS configuration and any auxiliary software 
     (compilers, libraries, database systems etc.) 
     If your experiment uses a virtual machine, describe the characteristics 
     of that virtual machine. 
-->
<!ELEMENT os (windows|linux|mac|sun|otheros)>
<!ATTLIST os softwares IDREFS #IMPLIED>

<!ELEMENT windows (version, (comment)?)>

<!ELEMENT version (#PCDATA)>

<!ELEMENT linux (distribname, distribno, kernel, comment?)>
<!-- Use distribname to specify the family name, e.g., SuSE, CentOS etc.
-->
<!ELEMENT distribname (#PCDATA)>

<!-- Use distribno to specify the distribution number, e.g., 2.2.10 etc. 
     Under Linux, the distribution number and kernel information can be 
     determined by typing uname -a.
-->
<!ELEMENT distribno (#PCDATA)>
<!ELEMENT kernel (#PCDATA)>

<!ELEMENT mac (version, kernel, comment?)>

<!ELEMENT sun (name, version, comment?)>

<!ELEMENT otheros (name, version, comment?)>

<!ELEMENT comment (#PCDATA)>

<!-- Use software to describe any software (other than the code you
     provided in the FTP site) needed in order to run or compile the code. 
     Examples include: compilers used to compile your code, 
     runtime engines, libraries, simulators, database systems it needs 
     to interact with, software for analyzing the data and producing 
     graphs etc. 
     If your experiment was run using a virtualization platform, 
     describe the virtual image player, and the actual virtual image used, 
     as two distinct pieces of software; be sure to include their URLs.
-->
<!ELEMENT software (name, function, version?, downloadURL?, comment?)>
<!ATTLIST software id ID #REQUIRED>

<!ELEMENT name (#PCDATA)>

<!-- Use function to briefly specify the role that this software plays 
     in the setting. This will enable e.g. replacing it with a similar 
     existing component if we are not able to obtain the exact software 
     you used. 
-->
<!ELEMENT function (#PCDATA)>

<!-- Use downloadURL to specify where a free or trial version 
     of the software can be found. 
-->
<!ELEMENT downloadURL (#PCDATA)>


<!-- Elements network and machineset should be used  for experiments 
     ran on several machines.
     Use machineset to specify a set of identical machines: mkey should be 
     a foreign key pointing to an existing declared machine element; 
     howmany should specify how many machines of this kind are part of 
     the machine set. 
-->
<!ELEMENT machineset EMPTY>
<!ATTLIST machineset mkey IDREF #REQUIRED howmany CDATA #REQUIRED>

<!-- Use network to specify a set of machines used in an experiment. 
     The network may include homogeneous subsets of identical machines, 
     each such subset being described by a machineset element. If all
     machines are different, use 1-sized machinesets. 
-->
<!ELEMENT network (machineset+, comment?)>
<!ATTLIST network id ID #REQUIRED type CDATA #REQUIRED>

<!-- For each experiment that we may reproduce, provide:  its main id 
     (typically "Figure X" or "Table Y"),  its secondary id if any (e.g.: 
     "left" or "top"), and: either the key of a machine, or the key of a 
     network, depending on the hardware used for this experiment. 
     'hw_recommended' specifies the system you used; optionally,
     'hw_minimal' and/or 'hw_alternative' specify minimal and/or alternative
     system specifications; please give further details in the 'variations'
     instructions.
-->
<!ELEMENT experiment (dataset*, install, howto, variations)>
<!ATTLIST experiment id1 CDATA #REQUIRED  id2 CDATA #IMPLIED
hw_recommended IDREF #REQUIRED hw_minimal IDREF #IMPLIED hw_alternative IDREF #IMPLIED>

<!-- Use dataset to specify the dataset(s) to be used in the experiment. 
     For each dataset, provide its download URL, or the path leading to 
     the file in your FTP space, or the information necessary to produce it 
     using a generator etc. 
     If the data set of the experiment is not available, supply a similar
     smaller synthetic one when possible. 
-->
<!ELEMENT dataset (#PCDATA)>

<!-- Specify what needs to be installed and how in order to perform 
      this experiment. If the installation is the same as for a previously 
      described experiment, just say so. -->
<!ELEMENT install (#PCDATA)>

<!-- Give the sequence of steps that need to be performed in order to 
     run the experiment. 
     Include: 
     - any necessary pre-processing steps
     - the commands actually performing the experiment
     - the number of runs if any
     - the operations needed to gather and analyse the results
     - the production of graphs corresponding to those of the paper. 
     If you cannot automatize producing the graphs, the numerical 
     results should be in a simple format acceptable for standard 
     plotting tools, e.g. CSV (comma-separated values).  
     
     The ideal description of a given step is the command line needed 
     to run it. 
-->
<!ELEMENT howto (#PCDATA)>
<!-- Please give instruction and/or recommendations how to vary and/or
     extend your experiments - e.g., by using different datasets,
     workloads, systems, parameters, etc. - beyond what you used for and
     presented in your paper.
-->
<!ELEMENT variations (#PCDATA)>

<!-- For all experiments which cannot be repeated due to IP, copyright or
     other issues, use a nonrepexperiment element to explain why. 
     Include primary and possibly secondary key as for repeatable 
     experiments. 
-->
<!ELEMENT nonrepexperiment (#PCDATA)>
<!ATTLIST nonrepexperiment id1 CDATA #REQUIRED id2 CDATA #IMPLIED>

=== TonyApuzzo/fuzzyjoin/fuzzyjoin-hadoop/src/test/scripts/rwe/SIGMOD-2010-RWE.xml
<!DOCTYPE experiments_description SYSTEM "SIGMOD-2010-RWE.dtd">
<!--
Copyright 2010 The Regents of the University of California

Licensed under the Apache License, Version 2.0 (the "License"); you
may not use this file except in compliance with the License.  You
may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS"; BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied.  See the License for the specific language governing
permissions and limitations under the License.

Author: Rares Vernica <rares (at) ics.uci.edu>
-->
<experiments_description>
  <paper id="146" title="Efficient Parallel Set-Similarity Joins Using MapReduce" />

  <!-- ------------ -->
  <!-- - HARDWARE - -->
  <!-- ------------ -->
  <machine id="asterix-master">
    <hardware>
      <class>server</class>
      <proc count="1"><!-- cat /proc/cpuinfo -->
        <make>Intel</make>
        <model>Xeon</model>
        <cores>1</cores>
        <bit>32</bit>
        <GHz>3.06</GHz>
      </proc>
      <memory megabytes="4096"/><!-- cat /proc/meminfo -->
      <disk count="1" RAIDlevel=""><!-- sudo lshw | grep -B 10 sda -->
        <interface>SCSI</interface>
        <gigabytes>73</gigabytes>
        <RPM>10000</RPM>
      </disk>
      <comment>Used for Hadoop NameNode and JobTracker.</comment>
    </hardware>
    <os softwares="java hadoop python pychart pssh">
      <linux>
        <distribname>Ubuntu</distribname><!-- cat /etc/issue -->
        <distribno>9.10</distribno>
        <kernel>2.6.31-19</kernel><!-- uname -a -->
      </linux>
    </os>
  </machine>

  <machine id="asterix-node">
    <hardware>
      <proc count="1">
        <make>Intel</make>
        <model>Xeon</model>
        <cores>4</cores>
        <bit>64</bit>
        <GHz>2.27</GHz>
      </proc>
      <memory megabytes="12288" />
      <disk count="4" RAIDlevel="">
        <interface>SATA</interface>
        <gigabytes>300</gigabytes>
        <RPM>10000</RPM>
      </disk>
    </hardware>
    <os softwares="java hadoop">
      <linux>
        <distribname>Ubuntu</distribname>
        <distribno>9.10</distribno>
        <kernel>2.6.31-19</kernel>
      </linux>
    </os>
  </machine>

  <network id="asterix" type="1 Gbit/s shared ethernet">
    <machineset mkey="asterix-master" howmany="1" />
    <machineset mkey="asterix-node" howmany="10" />
  </network>

  <!-- ------------ -->
  <!-- - SOFTWARE - -->
  <!-- ------------ -->
  <software id="java">
    <name>Sun JDK</name>
    <function>Compile and run source code</function>
    <version>6</version>
    <downloadURL>http://java.sun.com/javase/</downloadURL>
  </software>

  <software id="hadoop">
    <name>Apache Hadoop</name>
    <function>MapReduce framework</function>
    <version>0.20.1</version>
    <downloadURL>http://hadoop.apache.org/common/releases.html</downloadURL>
    <comment>Source code is compatible with Hadoop 0.18.3.</comment>
  </software>
 
 <software id="python">
    <name>Python</name>
    <function>Process experiment results and generate figures</function>
    <version>1.6</version>
    <downloadURL>http://www.python.org/download/</downloadURL>
  </software>

  <software id="pssh">
    <name>pssh</name>
    <function>Copy Hadoop configuration files and run commands on
    cluster nodes</function>
    <version>1.4.3</version>
    <downloadURL>http://www.theether.org/pssh/</downloadURL>
    <comment>On Ubuntu do: sudo apt-get install pssh</comment>
  </software>

  <!-- ---------------- -->
  <!-- - EXPERIMENTS  - -->
  <!-- ---------------- -->
  <experiment id1="Figure 8" hw_recommended="asterix">
    <dataset>DBLP x5-x25</dataset>
    <install>
IMPORTANT NOTE: The experiments scripts will format the HDFS, replace
the Hadoop configuration files and restart your Hadoop cluster. Please
backup your files and proceed with caution.

IMPORTANT NOTE: Please see fuzzyjoin-hadoop/README or
fuzzyjoin-hadoop/README.html first for general usage and a Quick Start
guide.

Compile
=======
Type:
cd fuzzyjoin/fuzzyjoin-hadoop ; ant

Setup
=====

Each Experiment consists of multiple Setups. For each Setup the Hadoop
cluster is stopped and reconfigured, and the HDFS is formatted. After
that, the data is loaded, duplicated and balanced. A new Setup is
initialized when the dataset, dataset size or number of nodes changes.

For example, in Figure 8 we use three dataset sizes DBLP x5, x10 and
x25. For each dataset size we initialize a new Setup.

Scripts Configuration
---------------------

First edit the fuzzyjoin/fuzzyjoin-hadoop/resources/util/conf.sh to
fit your system. You should set the following:

H_HOME -- path to your Hadoop instance

HDFS_FORMAT  -- command to remove the HDFS directories on each node

MEM_MAX -- maximum memory available at each node, excluding the memory
necessary to run the Hadoop daemons

CORE_MAX -- number of cores at each node (ideally this is the same as
the number of disks)

LOCAL_DATA_RAW_DBLP -- local path for the dblp.raw.txt; download from
http://asterix.ics.uci.edu/data/dblp.raw.txt.gz and unzip

LOCAL_DATA_RAW_CITESEERX -- local path for the csx.raw.txt; download
from http://asterix.ics.uci.edu/data/csx.raw.txt.gz and unzip

Hadoop Configuration
--------------------

In order to swap between different Hadoop configurations the scripts
for running the experiments assume a particular structure of the
hadoop/conf directory. The contents of our hadoop/conf directory is in
fuzzyjoin/fuzzyjoin-hadoop/resources/conf/hadoop/asterix. Use that
directory as a starting point. The following files and directories are
required in your hadoop/conf directory:

hadoop-env-batch.sh
core-site-batch.xml
hdfs-site-batch.xml
mapred-site-batch.xml
slaves-000/
  slaves-002 -- slaves for 2 nodes cluster size
  slaves-004 --            4
  slaves-008 --            8
  slaves-010 --           10
masters-000
  masters-010 -- master

Each of the "*-batch.(sh|xml)" file will replace its equivalent
without "-batch" in the file name. When a new Setup is initialized,
the non-"-batch" file is removed and a link between the "-batch" file
to the non-"-batch" file is created.

For example "core-site-batch.xml" will replace "core-site.xml". When
a new Setup is initialized, the "core-site.xml" file is removed and
"core-site.xml" becomes a symbolic link of "core-site-batch.xml".

The Hadoop settings used in the experiments are described in the paper
and set in the appropriate files in the
fuzzyjoin/fuzzyjoin-hadoop/resources/conf/hadoop/asterix directory.
    </install>
    <howto>
Type: 
cd fuzzyjoin/fuzzyjoin-hadoop/resources/rwe/ ; ./figure_8.sh 

Estimated running time: 3h

Results
-------

The script will generate the figures and print the path to them. The
numbers plotted in each figure are stored on files in the same
directories (or the child directories) as the figure. If applicable,
the script will also print the path to the file containing the numbers
in the table.

By default the results are stored in the
fuzzyjoin/fuzzyjoin-hadoop/exps directory. The structure of the "exps"
directory is the following:

 exps 
  |
  +- CLUSTER 
     | (e.g., asterix)
     |
     +- CASE 
        | (e.g. dblp, pub)
        | ("dblp" denotes the self-join case using the DBLP dataset,
        | "pub" denotes the R-S join case using the DBLP and CITESEERX
        | datasets)
        |
        +- EXPERIMENT_TYPE 
           | (e.g., perf, scaleup, speedup)
           | ("perf" denotes keeping the cluster size constant and
           | varying the dataset size, "scaleup" denotes keeping the
           | dataset size constant and varying the cluster size,
           | "speedup" denotes varying the dataset size and the
           | cluster size with the same factor)
           |
           +- STAGE
           |  | (e.g., 1, 2, 3 )
           |  | ("1" stands for Stage 1, etc.)
           |  |
           |  +- COMBINATION
           |     | (e.g., b, i, p)
           |     | (The letters have the following meaning:
           |     |  Stage 1: "b": BTO
           |     |           "i": OPTO
           |     |  Stage 2: "i": BK
           |     |           "p": PK
           |     |  Stage 3: "b": BRJ
           |     |           "i": OPRJ)
           |     |
           |     +- DATASET_SIZE.txt
           |     |  (e.g., 5.txt, 10.txt, 25.txt)
           |     |  (Running time of three runs for a certain dataset
           |     |  size. "5" denotes that the dataset was increased 5
           |     |  times, etc.)
           |     |
           |     +- DATASET_SIZE_log.txt
           |     |  (e.g., 5_log.txt, 10_log.txt, 25_log.txt)                  
           |     |  (Lists the name of the file which stores the log
           |     |  for three runs for a certain dataset size.) 
           |     |
           |     +- CLUSTER_SIZE.txt
           |     |  (e.g., 002.txt, 004.txt, 008.txt, 010.txt)
           |     |  (Running time of three runs for a certain cluster
           |     |  size. "002" denotes a cluster with 2 nodes, etc.)
           |     |
           |     +- DATASET_SIZE_log.txt
           |     |  (e.g., 002_log.txt, 004_log.txt, 008_log.txt, 010_log.txt)
           |     |  (Lists the name of the file which stores the log
           |     |  for three runs for a certain cluster size.)
           |     |
           |     +- avg.txt
           |        (Average for the considered dataset or cluster sizes.)
           |
           +- END-TO-END_COMBINATION
              | (e.g., bib, bpb, bpi)
              | ("bib" denotes the alternatives used in each stage,
              | first "b" denotes the alternative in the first stage,
              | "i" denotes the alternative for the second stage, and
              | second "b" denotes the alternative for the third
              | stage.)
              |
              +- avg.txt
